- name: Install Java
  apt:
    name: openjdk-11-jre
    state: present

- name: Add Elastic Search APT repository key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elastic Search APT repository key
   apt_repository:
     repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
     state: present
     filename: elastic-7.x

- name: Install Elastic Search
  apt:
    name: elasticsearch
    state: present

- name: Start Elastic Search
  service:
    name: elasticsearch
    state: started
    enabled: yes
